FROM rust:1.60.0 as builder
WORKDIR /usr/src/true-patriot-bot
ARG REPO_SOURCE_URL=https://github.com/zamazan4ik/true-patriot-bot
ARG CACHE_DATE=2020-01-01
RUN git clone --single-branch --branch main ${REPO_SOURCE_URL}
WORKDIR true-patriot-bot
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && apt-get clean
COPY --from=builder /usr/local/cargo/bin/true-patriot-bot /usr/local/bin/true-patriot-bot
CMD ["true-patriot-bot"]
